### ISSUE TITLE
An error occurred when I ran “CUDA_VISIBLE_DEVICES=0, python train_S3DIS.py”.

### ISSUE THREAD

**Issue by FAkor1** [vLAR-group/GrowSP#25]
computing point feats ....
computing pseduo labels...
labelled points ratio 0.85 clustering time: 35.67s
Superpoints oAcc 92.81 IoUs| mIoU 81.47 | 95.65 91.26 84.55 85.20 69.67 82.23 78.96 89.26 85.73 86.22 88.18 40.75 
Primitives oAcc 66.66 IoUs| mIoU 29.89 | 68.96 58.79 57.95 15.42  0.78 29.67 36.46 26.16 36.40  0.00 28.12  0.00 
Merging Primitives
Traceback (most recent call last):
  File "train_S3DIS.py", line 306, in <module>
    main(args, logger)
  File "train_S3DIS.py", line 99, in main
    o_Acc, m_Acc, s = eval(epoch, args, test_areas)
  File "/root/autodl-tmp/GrowSP-main/eval_S3DIS.py", line 118, in eval
    all_preds = torch.cat(preds).numpy()
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

**Comment by zhang-zihui** [comment]
Hi, this means that the list of "preds" is empty. Have you set your data path correctly?
